options_container = {
		'worldwide' : '',
		'usa' : 'country/us/',
		'india' : 'country/india/',
		'brazil' : 'country/brazil/',
		'france' : 'country/france/',
		'russia' : 'country/russia/',
		'spain' : 'country/spain/',
		'uk' : 'country/uk/',
		'argentina' : 'country/argentina/',
		'italy' : 'country/italy/',
		'colombia' : 'country/colombia/',
		'mexico' : 'country/mexico/',
		'peru' : 'country/peru/',
		'germany' : 'country/germany/',
		'iran' : 'country/iran/',
		'poland' : 'country/poland/',
		'south africa' : 'country/south-africa/',
		'ukraine' : 'country/ukraine/',
		'belgium' : 'country/belgium/',
		'chile' : 'country/chile/',
		'iraq' : 'country/iraq/',
		'indonesia' : 'country/indonesia/',
		'czechia' : 'country/czech-republic/',
		'netherlands' : 'country/netherlands/',
		'bangladesh' : 'country/bangladesh/',
		'turkey' : 'country/turkey/',
		'philippines' : 'country/philippines/',
		'romania' : 'country/romania/',
		'pakistan' : 'country/pakistan/',
		'saudi arabia' : 'country/saudi-arabia/',
		'israel' : 'country/israel/',
		'canada' : 'country/canada/',
		'morocco' : 'country/morocco/',
		'switzerland' : 'country/switzerland/',
		'portugal' : 'country/portugal/',
		'austria' : 'country/austria/',
		'nepal' : 'country/nepal/',
		'sweden' : 'country/sweden/',
		'ecuador' : 'country/ecuador/',
		'jordan' : 'country/jordan/',
		'hungary' : 'country/hungary/',
		'uae' : 'country/united-arab-emirates/',
		'panama' : 'country/panama/',
		'bolivia' : 'country/bolivia/',
		'kuwait' : 'country/kuwait/',
		'qatar' : 'country/qatar/',
		'dominican republic' : 'country/dominican-republic/',
		'costa rica' : 'country/costa-rica/',
		'kazakhstan' : 'country/kazakhstan/',
		'japan' : 'country/japan/',
		'armenia' : 'country/armenia/',
		'oman' : 'country/oman/',
		'belarus' : 'country/belarus/',
		'guatemala' : 'country/guatemala/',
		'lebanon' : 'country/lebanon/',
		'egypt' : 'country/egypt/',
		'bulgaria' : 'country/bulgaria/',
		'ethiopia' : 'country/ethiopia/',
		'serbia' : 'country/serbia/',
		'honduras' : 'country/honduras/',
		'venezuela' : 'country/venezuela/',
		'moldova' : 'country/moldova/',
		'croatia' : 'country/croatia/',
		'georgia' : 'country/georgia/',
		'slovakia' : 'country/slovakia/',
		'bahrain' : 'country/bahrain/',
		'greece' : 'country/greece/',
		'azerbaijan' : 'country/azerbaijan/',
		'tunisia' : 'country/tunisia/',
		'bosnia and herzegovina' : 'country/bosnia-and-herzegovina/',
		'libya' : 'country/libya/',
		'myanmar' : 'country/myanmar/',
		'kenya' : 'country/kenya/',
		'paraguay' : 'country/paraguay/',
		'uzbekistan' : 'country/uzbekistan/',
		'algeria' : 'country/algeria/',
		'ireland' : 'country/ireland/',
		'kyrgyzstan' : 'country/kyrgyzstan/',
		'palestine' : 'country/state-of-palestine/',
		'denmark' : 'country/denmark/',
		'nigeria' : 'country/nigeria/',
		'slovenia' : 'country/slovenia/',
		'singapore' : 'country/singapore/',
		'malaysia' : 'country/malaysia/',
		'north macedonia' : 'country/macedonia/',
		'ghana' : 'country/ghana/',
		'afghanistan' : 'country/afghanistan/',
		'lithuania' : 'country/lithuania/',
		'el salvador' : 'country/el-salvador/',
		'norway' : 'country/norway/',
		'albania' : 'country/albania/',
		's. korea' : 'country/south-korea/',
		'montenegro' : 'country/montenegro/',
		'luxembourg' : 'country/luxembourg/',
		'australia' : 'country/australia/',
		'cameroon' : 'country/cameroon/',
		'ivory coast' : 'country/cote-d-ivoire/',
		'finland' : 'country/finland/',
		'sri lanka' : 'country/sri-lanka/',
		'zambia' : 'country/zambia/',
		'madagascar' : 'country/madagascar/',
		'uganda' : 'country/uganda/',
		'senegal' : 'country/senegal/',
		'sudan' : 'country/sudan/',
		'mozambique' : 'country/mozambique/',
		'angola' : 'country/angola/',
		'namibia' : 'country/namibia/',
		'guinea' : 'country/guinea/',
		'french polynesia' : 'country/french-polynesia/',
		'maldives' : 'country/maldives/',
		'drc' : 'country/democratic-republic-of-the-congo/',
		'tajikistan' : 'country/tajikistan/',
		'latvia' : 'country/latvia/',
		'french guiana' : 'country/french-guiana/',
		'jamaica' : 'country/jamaica/',
		'cabo verde' : 'country/cabo-verde/',
		'haiti' : 'country/haiti/',
		'gabon' : 'country/gabon/',
		'botswana' : 'country/botswana/',
		'zimbabwe' : 'country/zimbabwe/',
		'estonia' : 'country/estonia/',
		'malta' : 'country/malta/',
		'guadeloupe' : 'country/guadeloupe/',
		'mauritania' : 'country/mauritania/',
		'cuba' : 'country/cuba/',
		'cyprus' : 'country/cyprus/',
		'bahamas' : 'country/bahamas/',
		'réunion' : 'country/reunion/',
		'syria' : 'country/syria/',
		'trinidad and tobago' : 'country/trinidad-and-tobago/',
		'eswatini' : 'country/swaziland/',
		'andorra' : 'country/andorra/',
		'malawi' : 'country/malawi/',
		'nicaragua' : 'country/nicaragua/',
		'djibouti' : 'country/djibouti/',
		'rwanda' : 'country/rwanda/',
		'congo' : 'country/congo/',
		'hong kong' : 'country/china-hong-kong-sar/',
		'iceland' : 'country/iceland/',
		'equatorial guinea' : 'country/equatorial-guinea/',
		'mayotte' : 'country/mayotte/',
		'guyana' : 'country/guyana/',
		'belize' : 'country/belize/',
		'car' : 'country/central-african-republic/',
		'martinique' : 'country/martinique/',
		'aruba' : 'country/aruba/',
		'somalia' : 'country/somalia/',
		'uruguay' : 'country/uruguay/',
		'mali' : 'country/mali/',
		'thailand' : 'country/thailand/',
		'gambia' : 'country/gambia/',
		'south sudan' : 'country/south-sudan/',
		'benin' : 'country/benin/',
		'togo' : 'country/togo/',
		'burkina faso' : 'country/burkina-faso/',
		'guinea-bissau' : 'country/guinea-bissau/',
		'sierra leone' : 'country/sierra-leone/',
		'yemen' : 'country/yemen/',
		'lesotho' : 'country/lesotho/',
		'new zealand' : 'country/new-zealand/',
		'chad' : 'country/chad/',
		'curaçao' : 'country/curacao/',
		'liberia' : 'country/liberia/',
		'san marino' : 'country/san-marino/',
		'niger' : 'country/niger/',
		'vietnam' : 'country/viet-nam/',
		'channel islands' : 'country/channel-islands/',
		'liechtenstein' : 'country/liechtenstein/',
		'sao tome and principe' : 'country/sao-tome-and-principe/',
		'sint maarten' : 'country/sint-maarten/',
		'gibraltar' : 'country/gibraltar/',
		'turks and caicos' : 'country/turks-and-caicos-islands/',
		'saint martin' : 'country/saint-martin/',
		'burundi' : 'country/burundi/',
		'taiwan' : 'country/taiwan/',
		'papua new guinea' : 'country/papua-new-guinea/',
		'comoros' : 'country/comoros/',
		'monaco' : 'country/monaco/',
		'eritrea' : 'country/eritrea/',
		'mongolia' : 'country/mongolia/',
		'tanzania' : 'country/tanzania/',
		'faeroe islands' : 'country/faeroe-islands/',
		'mauritius' : 'country/mauritius/',
		'bhutan' : 'country/bhutan/',
		'isle of man' : 'country/isle-of-man/',
		'cambodia' : 'country/cambodia/',
		'cayman islands' : 'country/cayman-islands/',
		'barbados' : 'country/barbados/',
		'bermuda' : 'country/bermuda/',
		'saint lucia' : 'country/saint-lucia/',
		'seychelles' : 'country/seychelles/',
		'caribbean netherlands' : 'country/caribbean-netherlands/',
		'brunei' : 'country/brunei-darussalam/',
		'antigua and barbuda' : 'country/antigua-and-barbuda/',
		'st. barth' : 'country/saint-barthelemy/',
		'st. vincent grenadines' : 'country/saint-vincent-and-the-grenadines/',
		'british virgin islands' : 'country/british-virgin-islands/',
		'dominica' : 'country/dominica/',
		'macao' : 'country/china-macao-sar/',
		'grenada' : 'country/grenada/',
		'fiji' : 'country/fiji/',
		'new caledonia' : 'country/new-caledonia/',
		'timor-leste' : 'country/timor-leste/',
		'vatican city' : 'country/holy-see/',
		'laos' : 'country/laos/',
		'saint kitts and nevis' : 'country/saint-kitts-and-nevis/',
		'greenland' : 'country/greenland/',
		'falkland islands' : 'country/falkland-islands-malvinas/',
		'saint pierre miquelon' : 'country/saint-pierre-and-miquelon/',
		'solomon islands' : 'country/solomon-islands/',
		'montserrat' : 'country/montserrat/',
		'western sahara' : 'country/western-sahara/',
		'marshall islands' : 'country/marshall-islands/',
		'anguilla' : 'country/anguilla/',
		'wallis and futuna' : 'country/wallis-and-futuna-islands/',
		'samoa' : 'country/samoa/',
		'vanuatu' : 'country/vanuatu/',
		'china' : 'country/china/'
	}